### ISSUE TITLE
Localize-Constrain-On-The-Fly

### ISSUE THREAD

**Issue by dimohamdy** [abdelrahman-egy/RTL-Localizer-IOS#3]
please check this
https://github.com/dimohamdy/iOS-Localize-Constrain

**Comment by abdelrahman-ahmed** [comment]
Good job, but this technique of localization has some drawbacks
1 - changing the constraints that way often results conflicts in the views constraints (check the debugger output)
2 - you have to handle all leading and trailing constraints your self as you did.
3 -  you have to do step 2 in all ViewControllers
4 -  you have to create localized strings for the strings appear on the views on yor storyboard.

In the other hand Apple's standard localization(Base Internationalization) as in my demo has pros and cons 
*Pros
1 -  iOS mirrors   the views constrains automatically for you based on the device language or the application language (if you set "AppleLanguages" key for your application), without having to right any code for that. 
2 - No constraints conflicts.
3 -  Xcode generates localized string file for each storyboard or .xib , and you can export these files and send them to translator and import them back after translation.
4 -  iOS load the localized strings that displayed on the views on the storyboard or .xib automatically based on the language
*Cons 
1 - you have to restart you application  if you change your application's language.

I think that Apple standard localization is efficient.

**Comment by dimohamdy** [comment]
as a Arab developer most of client ask to have localize without change of device language and without close the App

**Comment by dimohamdy** [comment]
About string localize it's simple on the fly ,i try to fix warning  of constrain change if you want to help make fork and send pull request 
Thanks FCI's Student

**Comment by abdelrahman-ahmed** [comment]
you're welcome . I will fork it

**Comment by dimohamdy** [comment]
i fix the warning ,and the code work in case of respect language and other cases

**Comment by abdelrahman-ahmed** [comment]
good job.
 what was wrong with the constraints ?

**Comment by dimohamdy** [comment]
when i remove and add constraints many times that make warning , i fix it by add and remove all constraints changes at once.

**Comment by abdelrahman-ahmed** [comment]
I f you did small change by adding one constraints as in the image below , that results constraints conflicts 
![screen shot 2015-10-03 at 6 04 22 pm](https://cloud.githubusercontent.com/assets/8409822/10263747/785c7048-69f9-11e5-8ad4-64bb6fafb057.png)

![screen shot 2015-10-03 at 6 04 38 pm](https://cloud.githubusercontent.com/assets/8409822/10263748/7867a116-69f9-11e5-86bc-9082f327b0d8.png)

![screen shot 2015-10-03 at 6 05 16 pm](https://cloud.githubusercontent.com/assets/8409822/10263749/78758344-69f9-11e5-890a-82a2b549f9cb.png)

and the UI is not mirrored correctly.

**Comment by abdelrahman-ahmed** [comment]
As in the storyboard snapshot , I extended the yellow button and give it trailing constraint with the parent view.

**Comment by dimohamdy** [comment]
can you commit in your fork and i will check it

**Comment by dimohamdy** [comment]
i got it and  i will fix it

**Comment by dimohamdy** [comment]
please check the constraint in new storyboard you must make un confused constrain to work correctly
